FROM node:22-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_APP_DEMO_MODE=false
ARG NEXT_PUBLIC_SUPPORT_WHATSAPP
ARG NEXT_PUBLIC_SUPPORT_TELEGRAM

ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV NEXT_PUBLIC_APP_DEMO_MODE=${NEXT_PUBLIC_APP_DEMO_MODE}
ENV NEXT_PUBLIC_SUPPORT_WHATSAPP=${NEXT_PUBLIC_SUPPORT_WHATSAPP}
ENV NEXT_PUBLIC_SUPPORT_TELEGRAM=${NEXT_PUBLIC_SUPPORT_TELEGRAM}

COPY package.json package-lock.json ./
COPY tsconfig.base.json ./
COPY scripts ./scripts
COPY apps ./apps
COPY packages ./packages

RUN npm ci \
  --include-workspace-root \
  --workspace @flixify/contracts \
  --workspace @flixify/ops-web \
  --no-audit \
  --fund=false
RUN npm run build -w @flixify/contracts \
  && npm run build -w @flixify/ops-web

ENV NODE_ENV=production
ENV OPS_WEB_PORT=3000

EXPOSE 3000

CMD ["npm", "run", "start", "-w", "@flixify/ops-web", "--", "--port", "3000"]
